### ISSUE TITLE
GNU Octave

### ISSUE THREAD

**Issue by iembry-USGS** [CALFEM/calfem-matlab#2]
Hi, can calfem also work with GNU Octave on any operating system?

If so, then how would you set the path?

Thank you.

Irucka Embry

**Comment by vedadalic** [comment]
Hi,

I just tried it on GNU Octave 4.0.2 in Ubuntu 16.04 LTS.

Most of the examples under "calfem-matlab/examples" work, however, the ones that don't work (exd2-exd4) don't work in MATLAB R2016a either.  

To set the path you can type the following in the GNU Octave Command Window:

addpath("~/path/to/calfem-matlab/fem")

where /path/to/calfem-matlab is the path to where you have cloned the repository.

Kind regards,
/Vedad

**Comment by iembry-USGS** [comment]
@ vedadalic Thank you. I tried your suggestion and it worked.
