### ISSUE TITLE
What is the license of calfem-matlab?

### ISSUE THREAD

**Issue by sewkokot** [CALFEM/calfem-matlab#5]
Dear developers of calfem-matlab,

I adapted some functions (among others eldisp2.m beam2crd.m beam2s.m) from matlab to python/matplotlib. Can we use them in another github repository:
https://github.com/OpenSeesPy-pip/openseespy-pip
https://github.com/zhuminjie/OpenSeesPyDoc

I know that python version of calfem has the MIT license, however for example `beam2crd.m` has not been ported yet in calfem-python.

Should I ask for an agreement to be able to modify and use interesting parts of calfem-matlab which are not present in calfem-python.

Thank you!

**Comment by jonaslindemann** [comment]
This is probarbly the longest response time ever, but CALFEM for MATLAB now has the same license as CALFEM for Python.
